<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>tinydms</title>
        <style>
            body {
                font-family: sans-serif;
            }
        </style>
    </head>
    <body>
        <h1>tinyDMS</h1>
        <div>a tiny document management system for PHP</div>

        <?php if (isset($name)) : ?>
            <!-- h2>Hello <?= htmlspecialchars($name); ?>!</h2 -->
        <?php else: ?>
            <!-- p>Try <a href="http://www.slimframework.com">SlimFramework</a></p -->
        <?php endif; ?>
    </body>
</html>
